# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.5
language: objective-c
# cache: cocoapods
# podfile: Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace template-ios.xcworkspace -scheme template-ios -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty

before_install:
- sudo gem install cocoapods
- pod install --repo-update
